paths:
  /table/query:
    post:
      operationId: "registered_operators.table.query.api"
      tags:
        - "Table"
      summary: "Trigger an execution engine job to query the metastore table"
      description: "Query metastore data"
      consumes:
        - application/json
      parameters:
        - name: query_string
          in: query
          required: true
          type: string
        - name: config_id
          in: query
          required: false
          type: string
        - name: database_name
          in: query
          required: true
          type: string
        - name: table_name
          in: query
          required: true
          type: string
        - name: log_level
          in: query
          enum: [ "info", "warning", "error", "debug", "trace", "fatal"]
          required: false
          type: string
          default: "info"
      responses:
        200:
          description: "Successful Query"
          schema:
            type: "string"
